import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ArrowRight, Check, ChevronRight, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";

const outcomes = ["Design ML delivery pipelines that make experimentation repeatable.", "Deploy models as services with clear observability and rollback paths.", "Operate the infrastructure that production AI systems depend on."];
const syllabus = ["A practical MLOps operating model", "Packaging, testing, and deploying model services", "Observability, retraining, and reliable operations"];

export default function CourseDetail() {
 return <main className="bg-[#f7f7f2]"><section className="border-b border-[#13201e]/10"><div className="page-shell py-5 text-xs text-[#68756f]"><Link className="hover:text-[#13201e]" to="/">Home</Link> <ChevronRight className="inline" size={13}/> <Link className="hover:text-[#13201e]" to="/courses">Courses</Link> <ChevronRight className="inline" size={13}/> MLOps Bootcamp</div></section>
 <section className="border-b border-[#13201e]/10 bg-[#e5ebdc]"><div className="page-shell grid gap-10 py-16 lg:grid-cols-[1.35fr_.65fr] lg:py-24"><div><p className="eyebrow">Intermediate · 32 hours</p><h1 className="mt-5 font-display text-5xl font-extrabold leading-[.94] tracking-[-.07em] sm:text-6xl">MLOps Bootcamp:<br/><span className="text-[#6d8700]">Build systems,</span><br/>not demos.</h1><p className="mt-7 max-w-2xl text-lg leading-7 text-[#52615a]">For engineers ready to move ML from notebook experiments into dependable, production-ready services.</p><div className="mt-8 flex flex-wrap gap-3 text-sm"><span className="rounded-full border border-[#13201e]/15 bg-[#f7f7f2] px-3 py-1.5">4.7 / 5 rating</span><span className="rounded-full border border-[#13201e]/15 bg-[#f7f7f2] px-3 py-1.5">Rating as of July 2026</span></div></div><aside className="self-end rounded-2xl border border-[#13201e] bg-[#13201e] p-6 text-[#f7f7f2] shadow-[8px_8px_0_#d9ff5a]"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b7c4ae]">Ready when you are</p><p className="mt-4 font-display text-2xl font-extrabold tracking-[-.04em]">Learn on Udemy.</p><p className="mt-2 text-sm leading-6 text-[#bcc7ba]">Enrollment, pricing, and full curriculum are available on the course page.</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-[#d9ff5a] px-5 py-3 text-sm font-bold text-[#13201e]">View on Udemy <ExternalLink size={15}/></button><p className="mt-3 text-center text-[10px] text-[#8e9e95]">Verified instructor referral link required before launch.</p></aside></div></section>
 <section className="page-shell grid gap-14 py-20 lg:grid-cols-2"><div><p className="eyebrow">The right fit</p><h2 className="section-title mt-4">Make sure it matches<br/>where you are.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#13201e]/15 bg-white p-6"><p className="font-display text-xl font-extrabold">This is for you if…</p><ul className="mt-5 space-y-3 text-sm leading-6 text-[#586760]"><li className="flex gap-2"><Check size={16} className="mt-1 shrink-0 text-[#789200]"/>You can work comfortably with Python and developer tooling.</li><li className="flex gap-2"><Check size={16} className="mt-1 shrink-0 text-[#789200]"/>You want to own the systems around ML, not just train models.</li></ul></div><div className="rounded-2xl border border-[#13201e]/15 p-6"><p className="font-display text-xl font-extrabold">Not the right fit if…</p><p className="mt-5 text-sm leading-6 text-[#586760]">You are looking for a conceptual overview with no implementation work, or are completely new to programming.</p></div></div></div><div><p className="eyebrow">What you’ll build</p><div className="mt-7 space-y-4">{outcomes.map((outcome,i)=><div key={outcome} className="flex gap-5 border-b border-[#13201e]/15 pb-5"><span className="font-mono text-xs text-[#789200]">0{i+1}</span><p className="font-display text-xl font-bold leading-6 tracking-[-.035em]">{outcome}</p></div>)}</div></div></section>
 <section className="border-y border-[#13201e]/10 bg-[#13201e] text-[#f7f7f2]"><div className="page-shell grid gap-10 py-20 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#d9ff5a]">Capstone project</p><h2 className="mt-4 font-display text-4xl font-extrabold leading-none tracking-[-.06em]">Build the production path.</h2><p className="mt-5 text-sm leading-6 text-[#b9c4b9]">Architect the delivery workflow that takes a tested model through packaging, deployment, monitoring, and iteration.</p></div><div className="rounded-2xl border border-white/25 p-6"><div className="grid items-center gap-3 sm:grid-cols-4"><div className="rounded-lg border border-[#d9ff5a] p-3 text-center text-xs font-bold">Model</div><ArrowRight className="mx-auto hidden text-[#d9ff5a] sm:block"/><div className="rounded-lg border border-white/35 p-3 text-center text-xs font-bold">Service</div><ArrowRight className="mx-auto hidden text-[#d9ff5a] sm:block"/><div className="rounded-lg border border-white/35 p-3 text-center text-xs font-bold sm:col-start-2">Observe</div></div><div className="mx-auto h-8 w-px bg-[#d9ff5a]"></div><div className="mx-auto max-w-[130px] rounded-lg border border-dashed border-white/35 p-3 text-center text-xs font-bold">Improve</div></div></div></section>
 <section className="page-shell grid gap-12 py-20 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Course map</p><h2 className="section-title mt-4">The syllabus highlights.</h2><Accordion type="single" collapsible className="mt-8 border-t border-[#13201e]/15">{syllabus.map((item,index)=><AccordionItem key={item} value={item}><AccordionTrigger className="font-display text-lg font-bold tracking-[-.025em] hover:no-underline"><span><span className="mr-4 font-mono text-xs text-[#789200]">0{index+1}</span>{item}</span></AccordionTrigger><AccordionContent className="text-sm leading-6 text-[#586760]">Focused lessons, real implementation decisions, and the exact tradeoffs engineers meet when systems leave the notebook.</AccordionContent></AccordionItem>)}</Accordion></div><aside className="rounded-2xl bg-[#d9ff5a] p-7"><p className="eyebrow">What’s next</p><h3 className="mt-4 font-display text-3xl font-extrabold leading-none tracking-[-.05em]">Keep going with the MLOps / AI Platform path.</h3><p className="mt-5 text-sm leading-6 text-[#43513a]">Turn this foundation into a complete, ordered route toward operating AI infrastructure.</p><Link to="/learning-paths" className="mt-7 inline-flex items-center gap-2 text-sm font-bold">View learning path <ArrowRight size={16}/></Link></aside></section>
 </main>;
}
